import { CIRCUIT } from "@/config/site";
import type { Advisory } from "@/types/advisory";
import type { Deal } from "@/types/deal";
import type { Place } from "@/types/place";

/**
 * Clearly-labelled demo data. Every record is fictional ("Demo ..." names);
 * no real businesses are represented. Coordinates are plausible points in
 * the Sepang / KLIA / Putrajaya area so the map demo feels realistic.
 */

const now = () => new Date();
const daysFromNow = (days: number) =>
  new Date(now().getTime() + days * 86_400_000).toISOString();
const daysAgo = (days: number) =>
  new Date(now().getTime() - days * 86_400_000).toISOString();

export const DEMO_CIRCUIT: Place = {
  id: "demo-circuit",
  slug: CIRCUIT.slug,
  name: CIRCUIT.name,
  category: "circuit",
  location: { lat: CIRCUIT.lat, lng: CIRCUIT.lng },
  verified: true,
  lastVerifiedAt: daysAgo(3),
  isOpenLate: false,
  isRaceDayRecommended: true,
  tags: ["race-venue"],
  description:
    "The race venue. Multiple gates operate on race day; allow extra time for security checks and walking from drop-off points.",
  isDemo: true,
};

export const DEMO_PLACES: Place[] = [
  DEMO_CIRCUIT,
  {
    id: "demo-hotel-airport",
    slug: "demo-airport-hotel",
    name: "Demo Airport Hotel",
    category: "hotel",
    location: { lat: 2.7456, lng: 101.7072 },
    priceLevel: 3,
    rating: 4.3,
    reviewCount: 1240,
    verified: true,
    lastVerifiedAt: daysAgo(5),
    isOpenLate: false,
    isRaceDayRecommended: true,
    tags: ["near-klia", "near-airport-rail", "easier-race-day-route"],
    description:
      "Demo hotel connected to the airport terminal. Short shuttle or taxi hop to the circuit on race day.",
    address: "Demo Terminal Road, KLIA (demo data)",
    isDemo: true,
  },
  {
    id: "demo-hotel-lakeside",
    slug: "demo-lakeside-hotel",
    name: "Demo Lakeside Hotel",
    category: "hotel",
    location: { lat: 2.9245, lng: 101.6871 },
    priceLevel: 2,
    rating: 4.0,
    reviewCount: 610,
    verified: true,
    lastVerifiedAt: daysAgo(9),
    isOpenLate: false,
    isRaceDayRecommended: false,
    tags: ["budget-friendly", "many-food-options", "car-recommended"],
    description:
      "Demo mid-range hotel in the Putrajaya lakeside area with plenty of food options nearby.",
    address: "Demo Lakeside Precinct, Putrajaya (demo data)",
    isDemo: true,
  },
  {
    id: "demo-hotel-city",
    slug: "demo-city-hotel",
    name: "Demo City Hotel",
    category: "hotel",
    location: { lat: 2.9936, lng: 101.7902 },
    priceLevel: 2,
    rating: 4.1,
    reviewCount: 890,
    verified: false,
    isOpenLate: false,
    isRaceDayRecommended: false,
    tags: ["best-for-nightlife", "good-for-groups"],
    description:
      "Demo hotel in the Cyberjaya/Puchong corridor. Longer race-day drive but livelier evenings.",
    address: "Demo Boulevard, Cyberjaya (demo data)",
    isDemo: true,
  },
  {
    id: "demo-hotel-trackside",
    slug: "demo-trackside-inn",
    name: "Demo Trackside Inn",
    category: "hotel",
    location: { lat: 2.7761, lng: 101.7205 },
    priceLevel: 1,
    rating: 3.7,
    reviewCount: 210,
    verified: true,
    lastVerifiedAt: daysAgo(4),
    isOpenLate: false,
    isRaceDayRecommended: true,
    tags: ["closest-to-circuit", "budget-friendly", "easier-race-day-route"],
    description:
      "Demo budget inn a short drive from the circuit gates. Books out early during race week.",
    address: "Demo Circuit Road, Sepang (demo data)",
    isDemo: true,
  },
  {
    id: "demo-food-local",
    slug: "demo-local-restaurant",
    name: "Demo Local Restaurant",
    category: "food",
    subcategory: "local-malaysian",
    location: { lat: 2.7488, lng: 101.7101 },
    priceLevel: 1,
    rating: 4.5,
    reviewCount: 320,
    verified: true,
    lastVerifiedAt: daysAgo(6),
    isOpenLate: true,
    isRaceDayRecommended: false,
    tags: ["local-malaysian", "late-night"],
    halalStatus: "halal-certified",
    vegetarianFriendly: true,
    openNow: true,
    closingTime: "02:00",
    description: "Demo 24-hour style local restaurant near the airport hotels.",
    isDemo: true,
  },
  {
    id: "demo-food-court",
    slug: "demo-food-court",
    name: "Demo Food Court",
    category: "food",
    subcategory: "food-court",
    location: { lat: 2.9261, lng: 101.6902 },
    priceLevel: 1,
    rating: 4.2,
    reviewCount: 150,
    verified: false,
    isOpenLate: false,
    isRaceDayRecommended: false,
    tags: ["food-court"],
    halalStatus: "not-specified",
    openNow: true,
    closingTime: "22:00",
    description: "Demo food court with mixed stalls near the lakeside hotels.",
    isDemo: true,
  },
  {
    id: "demo-food-cafe",
    slug: "demo-corner-cafe",
    name: "Demo Corner Café",
    category: "food",
    subcategory: "cafe",
    location: { lat: 2.9951, lng: 101.7889 },
    priceLevel: 2,
    rating: 4.4,
    reviewCount: 95,
    verified: false,
    isOpenLate: false,
    isRaceDayRecommended: false,
    tags: ["cafe"],
    halalStatus: "muslim-friendly",
    vegetarianFriendly: true,
    openNow: true,
    closingTime: "18:00",
    description: "Demo specialty coffee spot in the city cluster.",
    isDemo: true,
  },
  {
    id: "demo-food-latenight",
    slug: "demo-late-night-grill",
    name: "Demo Late Night Grill",
    category: "food",
    subcategory: "late-night",
    location: { lat: 2.7772, lng: 101.7188 },
    priceLevel: 1,
    rating: 4.0,
    reviewCount: 76,
    verified: true,
    lastVerifiedAt: daysAgo(2),
    isOpenLate: true,
    isRaceDayRecommended: true,
    tags: ["late-night", "local-malaysian"],
    halalStatus: "muslim-friendly",
    openNow: true,
    closingTime: "03:00",
    description: "Demo late-night mamak-style grill close to the circuit-area inns.",
    isDemo: true,
  },
  {
    id: "demo-transit-hub",
    slug: "demo-transit-hub",
    name: "Demo Transit Hub",
    category: "transit",
    subcategory: "airport-rail",
    transitMode: "airport-rail",
    location: { lat: 2.7431, lng: 101.7016 },
    verified: true,
    lastVerifiedAt: daysAgo(3),
    isOpenLate: false,
    isRaceDayRecommended: true,
    tags: ["airport-rail"],
    firstMileNote: "Follow signs from the arrivals hall to the rail platform (about 5 minutes indoors).",
    lastMileNote: "On race days, exit at this hub and follow event signage to the shuttle marshalling area.",
    requiresTransfer: true,
    raceDayAvailability: "Trains every 20 minutes; extended hours on race weekend (demo).",
    description: "Demo airport rail hub where race-day shuttles depart.",
    isDemo: true,
  },
  {
    id: "demo-transit-station-north",
    slug: "demo-north-station",
    name: "Demo North Station",
    category: "transit",
    subcategory: "ktm",
    transitMode: "ktm",
    location: { lat: 2.9402, lng: 101.7911 },
    verified: false,
    isOpenLate: false,
    isRaceDayRecommended: false,
    tags: ["ktm"],
    firstMileNote: "Taxis and ride-hailing pick up at the east exit.",
    lastMileNote: "No direct circuit connection; transfer to ride-hailing.",
    requiresTransfer: true,
    raceDayAvailability: "Normal weekend schedule (demo).",
    description: "Demo commuter rail station serving the northern hotels.",
    isDemo: true,
  },
  {
    id: "demo-event-shuttle",
    slug: "demo-event-shuttle",
    name: "Demo Event Shuttle Pickup",
    category: "transit",
    subcategory: "event-shuttle",
    transitMode: "event-shuttle",
    location: { lat: 2.7442, lng: 101.7035 },
    verified: true,
    lastVerifiedAt: daysAgo(1),
    isOpenLate: false,
    isRaceDayRecommended: true,
    tags: ["event-shuttle", "race-week-only"],
    firstMileNote: "Shuttle bay is beside the Demo Transit Hub taxi rank; look for event marshals.",
    lastMileNote: "Drops at the circuit shuttle apron, about 8 minutes' walk to the main gates.",
    requiresTransfer: false,
    raceDayAvailability: "Race weekend only, roughly every 15 minutes from 07:00 (demo).",
    advisoryMessage: "Queues peak 90 minutes before the race start (demo).",
    description: "Demo race-week shuttle pickup point. Curated record — not from a places API.",
    isDemo: true,
  },
  {
    id: "demo-parkandride",
    slug: "demo-park-and-ride",
    name: "Demo Park & Ride",
    category: "transit",
    subcategory: "park-and-ride",
    transitMode: "park-and-ride",
    location: { lat: 2.8103, lng: 101.7402 },
    verified: true,
    lastVerifiedAt: daysAgo(2),
    isOpenLate: false,
    isRaceDayRecommended: true,
    tags: ["park-and-ride", "race-week-only"],
    firstMileNote: "Drive in via the demo trunk road; parking marshals direct you to a bay.",
    lastMileNote: "Shuttle buses loop to the circuit every 20 minutes (demo).",
    requiresTransfer: true,
    raceDayAvailability: "Race weekend only, 06:30–23:00 (demo).",
    description: "Demo temporary park-and-ride site north of the circuit.",
    isDemo: true,
  },
  {
    id: "demo-essential-store",
    slug: "demo-convenience-store",
    name: "Demo Convenience Store",
    category: "essential",
    subcategory: "convenience-store",
    location: { lat: 2.7768, lng: 101.7212 },
    verified: false,
    isOpenLate: true,
    isRaceDayRecommended: false,
    tags: ["convenience-store", "24-hours"],
    openNow: true,
    description: "Demo 24-hour convenience store near the trackside inns.",
    isDemo: true,
  },
  {
    id: "demo-essential-clinic",
    slug: "demo-clinic",
    name: "Demo Clinic",
    category: "essential",
    subcategory: "clinic",
    location: { lat: 2.9238, lng: 101.6858 },
    verified: true,
    lastVerifiedAt: daysAgo(12),
    isOpenLate: false,
    isRaceDayRecommended: false,
    tags: ["clinic"],
    openNow: true,
    closingTime: "21:00",
    description: "Demo walk-in clinic in the lakeside precinct.",
    isDemo: true,
  },
  {
    id: "demo-essential-pharmacy",
    slug: "demo-pharmacy",
    name: "Demo Pharmacy",
    category: "essential",
    subcategory: "pharmacy",
    location: { lat: 2.9944, lng: 101.7921 },
    verified: false,
    isOpenLate: false,
    isRaceDayRecommended: false,
    tags: ["pharmacy"],
    openNow: true,
    closingTime: "22:00",
    description: "Demo pharmacy in the city cluster.",
    isDemo: true,
  },
  {
    id: "demo-essential-prayer",
    slug: "demo-prayer-room",
    name: "Demo Prayer Room",
    category: "essential",
    subcategory: "prayer-room",
    location: { lat: 2.7452, lng: 101.7048 },
    verified: true,
    lastVerifiedAt: daysAgo(7),
    isOpenLate: true,
    isRaceDayRecommended: false,
    tags: ["prayer-room"],
    description: "Demo surau located inside the transit hub concourse.",
    isDemo: true,
  },
];

export const DEMO_DEALS: Deal[] = [
  {
    id: "demo-deal-hotel",
    placeId: "demo-hotel-airport",
    placeName: "Demo Airport Hotel",
    placeSlug: "demo-airport-hotel",
    title: "Race-week late checkout (demo)",
    description: "Demo deal: free late checkout until 4 PM on race Sunday for direct bookings.",
    validFrom: daysAgo(10),
    validUntil: daysFromNow(14),
    redemptionInstructions: "Quote the demo code at check-in.",
    code: "DEMO-LATE",
    terms: "Demo terms: subject to availability. This is sample data, not a real offer.",
    sourceUrl: "https://example.com/demo-deal",
    verified: true,
    lastCheckedAt: daysAgo(2),
    isActive: true,
    isDemo: true,
  },
  {
    id: "demo-deal-food",
    placeId: "demo-food-local",
    placeName: "Demo Local Restaurant",
    placeSlug: "demo-local-restaurant",
    title: "Free teh tarik with any set meal (demo)",
    description: "Demo deal: show your race ticket for a free drink with any set meal.",
    validFrom: daysAgo(5),
    validUntil: daysFromNow(7),
    redemptionInstructions: "Show a race ticket before ordering.",
    terms: "Demo terms: one per customer. This is sample data, not a real offer.",
    sourceUrl: "https://example.com/demo-deal-2",
    verified: false,
    isActive: true,
    isDemo: true,
  },
];

export const DEMO_ADVISORIES: Advisory[] = [
  {
    id: "demo-advisory-road",
    title: "Race-day road restrictions around the circuit (demo)",
    description:
      "Demo advisory: the southern approach road operates one-way towards the circuit from 06:00 to 12:00 on race day. Expect diversions and allow extra time.",
    severity: "warning",
    placeId: "demo-circuit",
    placeName: CIRCUIT.name,
    startsAt: daysAgo(1),
    endsAt: daysFromNow(10),
    sourceUrl: "https://example.com/demo-advisory",
    verified: true,
    isActive: true,
    isDemo: true,
  },
  {
    id: "demo-advisory-shuttle",
    title: "Shuttle queue times peak before lights out (demo)",
    description:
      "Demo advisory: event shuttles from the Demo Transit Hub see 30–45 minute queues in the two hours before the race start. Travelling earlier is more reliable.",
    severity: "info",
    placeId: "demo-event-shuttle",
    placeName: "Demo Event Shuttle Pickup",
    startsAt: daysAgo(1),
    endsAt: daysFromNow(10),
    verified: true,
    isActive: true,
    isDemo: true,
  },
];
